--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 9.2.922
--   Created On : niedziela, 16 luty, 2014 
--   DBMS       : SQL Server 2008 
--   -------------------------------------------------- 

USE CustomerLoader;

--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_ARCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AccessRestriction DROP CONSTRAINT FK_ARCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_AccessRestriction_DRole') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AccessRestriction DROP CONSTRAINT FK_AccessRestriction_DRole;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_AccessRestriction_DAccessType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AccessRestriction DROP CONSTRAINT FK_AccessRestriction_DAccessType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Customer_DCategory') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Customer DROP CONSTRAINT FK_Customer_DCategory;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Customer_DForm') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Customer DROP CONSTRAINT FK_Customer_DForm;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Customer_DParticularForm') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Customer DROP CONSTRAINT FK_Customer_DParticularForm;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Customer_DCustomerType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Customer DROP CONSTRAINT FK_Customer_DCustomerType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Customer_NBPType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Customer DROP CONSTRAINT FK_Customer_NBPType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Customer_AMLCustomerType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Customer DROP CONSTRAINT FK_Customer_AMLCustomerType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Customer_DSegment') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Customer DROP CONSTRAINT FK_Customer_DSegment;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_AdressList_Customer') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AddressList DROP CONSTRAINT FK_AdressList_Customer;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_AddressList_AddressType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AddressList DROP CONSTRAINT FK_AddressList_AddressType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_AddressList_DCitizenshipCountry') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AddressList DROP CONSTRAINT FK_AddressList_DCitizenshipCountry;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_AddressList_DVoivodeship') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AddressList DROP CONSTRAINT FK_AddressList_DVoivodeship;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CBCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CustomerBranch DROP CONSTRAINT FK_CBCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CustomerBranch_DEntity') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CustomerBranch DROP CONSTRAINT FK_CustomerBranch_DEntity;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_GCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Giodo DROP CONSTRAINT FK_GCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Giodo_DConsentType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Giodo DROP CONSTRAINT FK_Giodo_DConsentType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CustomerGroup_DGroupType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CustomerGroup DROP CONSTRAINT FK_CustomerGroup_DGroupType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_GroupID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE GroupMember DROP CONSTRAINT FK_GroupID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_GMCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE GroupMember DROP CONSTRAINT FK_GMCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_GroupMember_DContributionType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE GroupMember DROP CONSTRAINT FK_GroupMember_DContributionType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_GroupMember_DRelationshipClass') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE GroupMember DROP CONSTRAINT FK_GroupMember_DRelationshipClass;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_HCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Handling0 DROP CONSTRAINT FK_HCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Handling0_DHandling0Definition') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Handling0 DROP CONSTRAINT FK_Handling0_DHandling0Definition;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Handling0ID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE HandlingList DROP CONSTRAINT FK_Handling0ID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_HandlingList_DHandlingDefinition') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE HandlingList DROP CONSTRAINT FK_HandlingList_DHandlingDefinition;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_HandlingList_DHandlingStatus') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE HandlingList DROP CONSTRAINT FK_HandlingList_DHandlingStatus;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_IndividualID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE IdentificationDoc DROP CONSTRAINT FK_IndividualID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_IdentificationDoc_DIdentificationType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE IdentificationDoc DROP CONSTRAINT FK_IdentificationDoc_DIdentificationType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_IdCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_IdCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_DTitle') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_DTitle;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_DCitizenshipCountry') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_DCitizenshipCountry;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_DSex') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_DSex;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_MaritalStatus') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_MaritalStatus;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_DEducation') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_DEducation;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_DOccupation') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_DOccupation;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_DIncome') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_DIncome;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_DPost') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_DPost;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_DIncomeCurrency') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_DIncomeCurrency;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Individual_DSeperateProperty') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Individual DROP CONSTRAINT FK_Individual_DSeperateProperty;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_InCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Institutional DROP CONSTRAINT FK_InCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Inistitutional_DAccountForm') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Institutional DROP CONSTRAINT FK_Inistitutional_DAccountForm;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Institutional_DMIFID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Institutional DROP CONSTRAINT FK_Institutional_DMIFID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Institutional_DClaimsCategory') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Institutional DROP CONSTRAINT FK_Institutional_DClaimsCategory;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Institutional_DRating') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Institutional DROP CONSTRAINT FK_Institutional_DRating;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Institutional_DInvestmentRiskProfile') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Institutional DROP CONSTRAINT FK_Institutional_DInvestmentRiskProfile;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Institutional_DRiskGroup') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Institutional DROP CONSTRAINT FK_Institutional_DRiskGroup;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PCLCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PredefCustomerList DROP CONSTRAINT FK_PCLCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CdCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CustomerDoc DROP CONSTRAINT FK_CdCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_BCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Blocade DROP CONSTRAINT FK_BCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_RCustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Relationship DROP CONSTRAINT FK_RCustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Relationship_DRelationshipType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Relationship DROP CONSTRAINT FK_Relationship_DRelationshipType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Relationship_CustomerID') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Relationship DROP CONSTRAINT FK_Relationship_CustomerID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DAccount_Form_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DAccountForm DROP CONSTRAINT FK_DAccount_Form_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DAMLCustomerType_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DAMLCustomerType DROP CONSTRAINT FK_DAMLCustomerType_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DCategory') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DCategory DROP CONSTRAINT FK_DCategory;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DClaimsCategory_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DClaimsCategory DROP CONSTRAINT FK_DClaimsCategory_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DConsentType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DConsentType DROP CONSTRAINT FK_DConsentType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DCustomerType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DCustomerType DROP CONSTRAINT FK_DCustomerType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DForm') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DForm DROP CONSTRAINT FK_DForm;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DRiskInvestmentProfile_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DInvestmentRiskProfile DROP CONSTRAINT FK_DRiskInvestmentProfile_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DMIFID_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DMIFID DROP CONSTRAINT FK_DMIFID_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DNBPType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DNBPType DROP CONSTRAINT FK_DNBPType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DParticularForm') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DParticularForm DROP CONSTRAINT FK_DParticularForm;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DPKD_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DPKD DROP CONSTRAINT FK_DPKD_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DRating_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DRating DROP CONSTRAINT FK_DRating_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DRiskGroup_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DRiskGroup DROP CONSTRAINT FK_DRiskGroup_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DSegment_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DSegment DROP CONSTRAINT FK_DSegment_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DEntity_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DEntity DROP CONSTRAINT FK_DEntity_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DRole_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DRole DROP CONSTRAINT FK_DRole_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DAT_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DAccessType DROP CONSTRAINT FK_DAT_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DCT_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DContributionType DROP CONSTRAINT FK_DCT_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DRT_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DRelationshipType DROP CONSTRAINT FK_DRT_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DGT_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DGroupType DROP CONSTRAINT FK_DGT_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DRC_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DRelationshipClass DROP CONSTRAINT FK_DRC_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DH0D_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DHandling0Definition DROP CONSTRAINT FK_DH0D_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DHS_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DHandlingStatus DROP CONSTRAINT FK_DHS_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DIC_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DIncomeCurrency DROP CONSTRAINT FK_DIC_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DP_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DPost DROP CONSTRAINT FK_DP_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DCC_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DCitizenshipCountry DROP CONSTRAINT FK_DCC_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DE_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DEducation DROP CONSTRAINT FK_DE_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DHD_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DHandlingDefinition DROP CONSTRAINT FK_DHD_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DI_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DIncome DROP CONSTRAINT FK_DI_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DMS_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DMaritalStatus DROP CONSTRAINT FK_DMS_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DO_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DOccupation DROP CONSTRAINT FK_DO_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DSP_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DSeparateProperty DROP CONSTRAINT FK_DSP_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DAddressType_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DAddressType DROP CONSTRAINT FK_DAddressType_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DVoivodeship_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DVoivodeship DROP CONSTRAINT FK_DVoivodeship_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DS_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DSex DROP CONSTRAINT FK_DS_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DT_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DTitle DROP CONSTRAINT FK_DT_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DIdT_Dictionary') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DIdentificationType DROP CONSTRAINT FK_DIdT_Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DAlias_D0Alias') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DAlias DROP CONSTRAINT FK_DAlias_D0Alias;


--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AccessRestriction') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE AccessRestriction;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Customer') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Customer;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AddressList') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE AddressList;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CustomerBranch') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CustomerBranch;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Giodo') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Giodo;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CustomerGroup') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CustomerGroup;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('GroupMember') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE GroupMember;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Handling0') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Handling0;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('HandlingList') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE HandlingList;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('IdentificationDoc') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IdentificationDoc;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Individual') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Individual;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Institutional') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Institutional;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PredefCustomerList') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PredefCustomerList;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CustomerDoc') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CustomerDoc;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Blocade') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Blocade;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Relationship') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Relationship;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DAccountForm') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DAccountForm;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DAMLCustomerType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DAMLCustomerType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DCategory') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DCategory;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DClaimsCategory') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DClaimsCategory;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DConsentType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DConsentType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DCustomerType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DCustomerType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DForm') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DForm;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DInvestmentRiskProfile') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DInvestmentRiskProfile;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DMIFID') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DMIFID;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DNBPType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DNBPType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DParticularForm') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DParticularForm;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DPKD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DPKD;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DRating') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DRating;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DRiskGroup') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DRiskGroup;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DSegment') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DSegment;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Dictionary') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Dictionary;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DEntity') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DEntity;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DRole') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DRole;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DAccessType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DAccessType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DContributionType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DContributionType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DRelationshipType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DRelationshipType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DGroupType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DGroupType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DRelationshipClass') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DRelationshipClass;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DHandling0Definition') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DHandling0Definition;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DHandlingStatus') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DHandlingStatus;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DIncomeCurrency') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DIncomeCurrency;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DPost') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DPost;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DCitizenshipCountry') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DCitizenshipCountry;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DEducation') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DEducation;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DHandlingDefinition') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DHandlingDefinition;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DIncome') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DIncome;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DMaritalStatus') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DMaritalStatus;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DOccupation') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DOccupation;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DSeparateProperty') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DSeparateProperty;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DAddressType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DAddressType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DVoivodeship') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DVoivodeship;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DSex') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DSex;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DTitle') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DTitle;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DIdentificationType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DIdentificationType;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('D0Alias') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE D0Alias;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DAlias') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DAlias;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Pkd') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Pkd;


--  Create Tables 
CREATE TABLE AccessRestriction ( 
	AccessRestrictionID int NOT NULL,
	CustomerID int NOT NULL,
	AccessCode nvarchar(30) NOT NULL,
	Role tinyint NOT NULL,    --  DRole 1. Doradca 2. Dyrektor oddzia³u 3. Kierownik placówki 4. Naczelnik 5. Kasjer 6. Skarbnik 7. Pracownik zaplecza 
	EntityAccessRestriction int NOT NULL,    --  DEntity 199999 Dowolny oddzia³ 100000 Centrala 200000 Oddzia³ MPK Klienta 3RRxxx Oddzia³ xxx w regionie RR 4RR000 Oddzia³y w ramach regionu 
	AccessType tinyint NOT NULL,    --  DAccessType 1. Pe³ny dostêp 2. Tylko operacje bez widocznoœci danych wra¿liwych (w tym pracownicy banku) 
	ARValidFrom datetime,
	ARValidTo datetime
);

CREATE TABLE Customer ( 
	CustomerID int NOT NULL,
	CustomerModulo int NOT NULL,    --  Algorytm Luhna 
	Category tinyint DEFAULT 0 NOT NULL,    --  DCategory 0. klient potencjalny 1. klient rzeczywisy 
	Blocade bit DEFAULT 0,
	Name nvarchar(70) NOT NULL,
	RegistrationDate datetime NOT NULL,
	Form tinyint NOT NULL,    --  DForm 1. Osoba prawna 2. Jednostka organizacyjna niemaj¹ca osobowoœci prawnej 3. Osoba fizyczna prowadz¹ca dzia³alnoœæ gospodarcz¹ 
	ParticularForm smallint DEFAULT 0 NOT NULL,    --  DParticularForm Lista dla Finrep i Corep 
	Type tinyint DEFAULT 0 NOT NULL,    --  DCustomerType 1. pojedynczy 2. zbiorowy 
	NBPType smallint DEFAULT 0 NOT NULL,    --  DNBPType Wg zestawienia dla NBP 
	Segment tinyint NOT NULL,    --  DSegment 1. indywidualny 2. rolnik 3. podmiot gospodarczy 4. gospodarstwo rolne 5. bank grupy BPS 
	ResidenceStatus bit DEFAULT 0 NOT NULL,    --  DTakNie 
	ResidenceCountry tinyint NOT NULL,    --  DResidenceCountry 
	Ekz nvarchar(12),
	TaxResidenceCountry tinyint NOT NULL,    --  DResidenceCountry 
	AMLCustomerType tinyint DEFAULT 0 NOT NULL,    --  DAMLCustomerType 
	WithholdingInterestTax bit DEFAULT 0 NOT NULL,    --  DTakNie 
	TaxExemptionScheme bit DEFAULT 0,    --  DTakNie 
	ModificationDate datetime NOT NULL,
	UserID int NOT NULL,
	AuthorisationDate datetime,
	AuthorisationID int
);

CREATE TABLE AddressList ( 
	AdressID int NOT NULL,
	CustomerID int NOT NULL,
	Status bit DEFAULT 0 NOT NULL,    --  DStatus 0. nieaktywny 1. aktywny 
	AddressType tinyint NOT NULL,    --  DAddressType 0. sta³y 1. korespondencyjny 2. e-mail 3. nr telefonu SMS 4. nr jednostki organizacyjnej banku 5. SWIFT 6. Telefon domowy 7. Telefon s³u¿bowy 8. Telefon komórkowy 9. Fax 10. Telex 
	AddressName nvarchar(70) NOT NULL,    --     
	Street nvarchar(35),
	House nvarchar(4),
	ApartmentNumber nvarchar(4),
	ZipCode nvarchar(6),
	City nvarchar(35),
	Voivodeship tinyint,    --  DVoivodeship Tabela województw 
	Community nvarchar(15),
	AddressCountry tinyint,    --  DCitizenshipCountry 
	ValidFrom date,
	ValidTo date
);

CREATE TABLE CustomerBranch ( 
	CustomerBranchID int NOT NULL,
	CustomerID int NOT NULL,
	HistoricalModulo int,    --  Modulo10 Algorytm Luhna 
	Entity int NOT NULL,
	ConsultantID int NOT NULL,    --  Dane z EmployeeList 
	ValidTo datetime
);

CREATE TABLE Giodo ( 
	GiodoID int NOT NULL,
	CustomerID int NOT NULL,
	ConsentType tinyint NOT NULL,    --  DConsentType 0. Zgoda na przechowywanie i przetwarzanie danych osobowych 1. Zgoda na marketing produktów Banku 2. Zgoda na przetwarzanie danych osobowych w celach marketingowych w ramach Banku 3. Zgoda na otrzymywanie korespondencji drog¹ elektroniczn¹ 4. Zgoda na profilowanie klienta 
	ConsentDate datetime,
	CancellationDate datetime
);

CREATE TABLE CustomerGroup ( 
	GroupID int NOT NULL,
	Name nvarchar(45) NOT NULL,
	Type tinyint NOT NULL,    --  DGroupeType 
	ModificationDate datetime NOT NULL,
	UserID int NOT NULL
);

CREATE TABLE GroupMember ( 
	GroupMemberID int NOT NULL,
	GroupID int NOT NULL,
	CustomerID int NOT NULL,
	ContributionType tinyint NOT NULL,    --  DContributionType 
	ContributionAmount money,
	ContributionPercentage numeric(6,3),
	RelationshipClass tinyint    --  DRelationshipClass 1. Klient grupowy 2. Grupa kapita³owa 3. Powi¹zania kapita³owe 4. Powi¹zania organizacyjne 5. Powi¹zania gospodarcze 6. Powi¹zania personalne 7. Wspólnota maj¹tkowa 8. Upowa¿nienie 9. W³aœcicielskie 10. Beneficjent rzeczywisty 11. Grupa finansowa 12. Akcjonariusz 
);

CREATE TABLE Handling0 ( 
	Handling0ID int NOT NULL,
	Handling0 int,    --  DHandling0Definition 
	CustomerID int NOT NULL,
	FrameAgreementTemplate int,    --  DAgreementTemplate 
	FrameAgreementNo nvarchar(20),
	EffectiveDate datetime,
	TerminationType tinyint DEFAULT 0,    --  DTerminationType 0. trwa 1. terminowo 2. zerwanie przez klienta 3. zerwanie przez bank 
	TerminationDate datetime
);

CREATE TABLE HandlingList ( 
	HandlingListID int NOT NULL,
	Handling0ID int NOT NULL,
	Handling int NOT NULL,    --  DHandlingDefinition 
	Stability bit NOT NULL,    --  DTakNie 
	Status tinyint DEFAULT 0 NOT NULL,    --  DHandlingStatus 0. Oferowana 1. Za³o¿ona 2. Zakoñczona 
	StatusDateChange datetime NOT NULL
);

CREATE TABLE IdentificationDoc ( 
	IdentificationDocID int NOT NULL,
	IndividualID int NOT NULL,
	IdentificationType tinyint NOT NULL,    --  DIdentification 1. dowód osobisty 2. paszport polski 3. dowód osobosty zagraniczny 4. paszport zagraniczny 5. Legitymacja ucznioska/studencka 
	IdetificationNumber nvarchar(20) NOT NULL,
	ValidTo date
);

CREATE TABLE Individual ( 
	IndividualID int NOT NULL,
	CustomerID int NOT NULL,
	LastName nvarchar(35) NOT NULL,
	FirstNames nvarchar(35) NOT NULL,
	FamilyName nvarchar(35),
	MaidenName nvarchar(35),
	Minor bit,    --  DTakNie 
	Incapacitated bit,    --  DTakNie 
	Title tinyint,    --  DTitle 1. Pan 2. Pani 3. [         ]   {blank} 
	DeathCheck bit DEFAULT 0,    --  1 = zmar³a 
	DeathDate date,
	Citizenship tinyint DEFAULT 'PL' NOT NULL,    --  DCitizenshipCountry 
	Pesel nvarchar(11),
	BirthDate date NOT NULL,
	Sex tinyint,    --  DSex 
	MaritalStatus tinyint,    --  DMaritalStatus 1. panna/kawaler 2. ¿onaty/mê¿atka 3. kohabitacja 4. separacja 5. rozwiedziony/rozwiedziona 6. wdowiec/wdowa 7. pozosta³e 8. nieznane 
	Education tinyint,    --  DEducation 0. niepe³ne i podstawowe 1. zasadnicze zawodowe 2. œrednie 3. pomaturalne 4. wy¿sze (licencjat i in¿ynier) 5. wy¿sze magisterskie 6. podyplomowe 7. inne 8. nieznane 
	Occupation tinyint,    --  DOccupation Uk³ad s³ownika zgodny z BIK 
	Income tinyint,    --  DIncome Uk³ad s³ownika dla BIK 
	Workplace nvarchar(70),
	WorkplaceAddress nvarchar(70),
	Post smallint,    --  DPost Uk³ad ze s³ownika DD 
	OccupationYearStart nchar(4),
	ChildrenNumber tinyint,    --  >=0 
	DependentsNumber tinyint,    --  >=0 
	AnnualNetIncome money,
	IncomeCurrency smallint DEFAULT 985,    --  DIncomeCurrency Numeracja zgodna z ISO 
	SeparateProperty tinyint DEFAULT 99    --  DSeparateProperty 0. Nie dotyczy 1. Wspólnota maj¹tkowa 2. Rozdzielnoœæ maj¹tkowa 99. Nieznane 
);
CREATE TABLE Institutional ( 
	InstitutionalID int NOT NULL,
	CustomerID int NOT NULL,
	Nip nvarchar(12),    --  Liczba poprzedzona symbolem kraju  
	Regon nvarchar(14),
	Krs nvarchar(50),
	Ceidg nvarchar(50),
	LaunchDate date,    --  <=0 LaunchDate <= YEAR(NOW()) 
	AccountingForm tinyint,    --  DAccountingForm 1. Uproszczona 2. Pe³na 
	EmployessNumber int,    --  >=0 
	LastYearEmployessNumber int,
	TotalAssets money,
	LastYearTotalAssets money,
	AnnualNetTurnover money,
	LastYearAnnualNetTurnover money,
	FinancialStatementCurrency smallint DEFAULT 985,    --  DCurrency 
	LastYearFinancialStatementCurrency smallint DEFAULT 985,
	FinancialStatementDate date,
	LastYearFinancialStatementDate date,
	Mifid tinyint,    --  DMIFID 
	RiskGroup tinyint,    --  DRiskGroup 
	DueCategory tinyint,    --  DClaimsCategory 
	CustomerRating tinyint,    --  DRating 
	InvestmentRiskProfile tinyint    --  DInvestmentRiskProfile 
);

CREATE TABLE PredefCustomerList ( 
	PredefAddressID int NOT NULL,
	CustomerID int NOT NULL,
	ShortName nvarchar(10) NOT NULL,
	Name nvarchar(70) NOT NULL,
	Address nvarchar(70),
	AccountIBAN nvarchar(28) NOT NULL
);

CREATE TABLE CustomerDoc ( 
	DocumentID int NOT NULL,
	ArchiveDocID bigint,
	CustomerID int NOT NULL,
	DocDescription nvarchar(100),
	ValidTo date
);

CREATE TABLE Blocade ( 
	BlocadeID smallint NOT NULL,
	CustomerID int NOT NULL,
	BlocadeType smallint,    --  DBlocadeType 0. Niezablokowany 1. PEP 2. AML 3. Zastrze¿enie dokumentów 4. Wyp³aty 5. Wp³aty 6. Wp³aty i wyp³aty 
	ValidFrom datetime,
	ValidTo datetime
);

CREATE TABLE Relationship ( 
	RelationshipID int NOT NULL,
	CustomerID int NOT NULL,
	RelationshipCustomerID int NOT NULL,
	RelationshipType tinyint NOT NULL,    --  DRelationshipType 
	TerminationDate datetime
);

CREATE TABLE DAccountForm ( 
	DAccountFormID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DAMLCustomerType ( 
	DAMLCustomerTypeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DCategory ( 
	DCategoryID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DClaimsCategory ( 
	DClaimsCategoryID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DConsentType ( 
	DConsentTypeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DCustomerType ( 
	DCustomerTypeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DForm ( 
	DFormID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DInvestmentRiskProfile ( 
	DInvestmentRiskProfileID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DMIFID ( 
	DMIFIDID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DNBPType ( 
	DNBPTypeID smallint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DParticularForm ( 
	DParticularFormID smallint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DPKD ( 
	DPKDID int NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(250),
	ShortName nvarchar(50)
);

CREATE TABLE DRating ( 
	DRatingID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DRiskGroup ( 
	DRiskGroupID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DSegment ( 
	DSegmentID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,
	ValidTo datetime,
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE Dictionary ( 
	DictionaryID int NOT NULL,
	DictionaryName nvarchar(50),
	BusinessName nvarchar(100),
	ModificationDate datetime,
	UserID int,
	AuthorisationID int
);

CREATE TABLE DEntity ( 
	DEntityID int NOT NULL,
	DctionaryID int NOT NULL,
	ValidFrom datetime,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	EntityShortName nvarchar(50)
);

CREATE TABLE DRole ( 
	DRoleID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime,    --  Parametr istotny tylko w trakcie zmiany 
	ValidTo datetime,    --  Parametr istotny tylko w trakcie zmiany 
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DAccessType ( 
	DAccessTypeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DContributionType ( 
	DContributionTypeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DRelationshipType ( 
	DRelationshipTypeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DGroupType ( 
	DGroupTypeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DRelationshipClass ( 
	DRelationshipClassID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DHandling0Definition ( 
	DHandling0DefinitionID int NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DHandlingStatus ( 
	DHandlingStatusID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DIncomeCurrency ( 
	DIncomeCurrencyID smallint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DPost ( 
	DPostID smallint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DCitizenshipCountry ( 
	DCitizenshipCountryID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DEducation ( 
	DEducationID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DHandlingDefinition ( 
	DHandlingDefinitionID int NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DIncome ( 
	DIncomeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DMaritalStatus ( 
	DMaritalStatusID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DOccupation ( 
	DOccupationID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DSeparateProperty ( 
	DSeparatePropertyID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DAddressType ( 
	DAddressTypeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DVoivodeship ( 
	DVoivodeshipID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DSex ( 
	DSexID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DTitle ( 
	DTitleID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE DIdentificationType ( 
	DIdentificationTypeID tinyint NOT NULL,
	DictionaryID int NOT NULL,
	ValidFrom datetime NOT NULL,    --  Parametr istotny tylko przy zmianie 
	ValidTo datetime,    --  Parametr istotny tylko przy zmianie  
	Name nvarchar(150),
	ShortName nvarchar(50)
);

CREATE TABLE D0Alias ( 
	D0AliasID int NOT NULL,
	DAliasID int,
	Language nvarchar(2) DEFAULT 'PL',
	ModificationDate datetime,
	UserID int,
	AuthorisationID bigint
);

CREATE TABLE DAlias ( 
	DAliasID int NOT NULL,
	D0AliasID int,
	DbName nvarchar(50),
	EntityName nvarchar(50),
	ColumnName nvarchar(50),
	ColumnAliasName nvarchar(140),
	ShortColumnAliasName nvarchar(50)
);

CREATE TABLE Pkd ( 
	PkdID int NOT NULL,
	InstitutionalID int,
	Pkd int,    --  DPKD 
	PkdDescription nvarchar(150),
	MainPkd bit    --  DTakNie 
);

BULK INSERT dbo.DAddressType FROM 'C:/ITRLoader/DAddressType.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.AccessRestriction FROM 'C:/ITRLoader/AccessRestriction.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.Customer FROM 'C:/ITRLoader/Customer.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.AddressList FROM 'C:/ITRLoader/AddressList.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.CustomerBranch FROM 'C:/ITRLoader/CustomerBranch.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.Giodo FROM 'C:/ITRLoader/Giodo.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.CustomerGroup FROM 'C:/ITRLoader/CustomerGroup.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.GroupMember FROM 'C:/ITRLoader/GroupMember.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.Handling0 FROM 'C:/ITRLoader/Handling0.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.HandlingList FROM 'C:/ITRLoader/HandlingList.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.IdentificationDoc FROM 'C:/ITRLoader/IdentificationDoc.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.Individual FROM 'C:/ITRLoader/Individual.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.Institutional FROM 'C:/ITRLoader/Institutional.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.PredefCustomerList FROM 'C:/ITRLoader/PredefCustomerList.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.CustomerDoc FROM 'C:/ITRLoader/CustomerDoc.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.Blocade FROM 'C:/ITRLoader/Blocade.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.Relationship FROM 'C:/ITRLoader/Relationship.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DAccountForm FROM 'C:/ITRLoader/DAccountForm.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DAMLCustomerType FROM 'C:/ITRLoader/DAMLCustomerType.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DCategory FROM 'C:/ITRLoader/DCategory.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DClaimsCategory FROM 'C:/ITRLoader/DClaimsCategory.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DConsentType FROM 'C:/ITRLoader/DConsentType.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DCustomerType FROM 'C:/ITRLoader/DCustomerType.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DForm FROM 'C:/ITRLoader/DForm.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DInvestmentRiskProfile FROM 'C:/ITRLoader/DInvestmentRiskProfile.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DMIFID FROM 'C:/ITRLoader/DMIFID.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DNBPType FROM 'C:/ITRLoader/DNBPType.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DParticularForm FROM 'C:/ITRLoader/DParticularForm.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DPKD FROM 'C:/ITRLoader/DPKD.txt' 
WITH (FIRSTROW = 2,  CODEPAGE = 'ACP');

BULK INSERT dbo.DRating FROM 'C:/ITRLoader/DRating.txt' 
WITH (FIRSTROW = 2, LASTROW = 250, CODEPAGE = 'ACP');

BULK INSERT dbo.DRiskGroup FROM 'C:/ITRLoader/DRiskGroup.txt' 
WITH (FIRSTROW = 2, LASTROW = 250, CODEPAGE = 'ACP');

BULK INSERT dbo.DSegment FROM 'C:/ITRLoader/DSegment.txt' 
WITH (FIRSTROW = 2, LASTROW = 250, CODEPAGE = 'ACP');

BULK INSERT dbo.Dictionary FROM 'C:/ITRLoader/Dictionary.txt' 
WITH (FIRSTROW = 2, LASTROW = 250, CODEPAGE = 'ACP');

BULK INSERT dbo.DEntity FROM 'C:/ITRLoader/DEntity.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DRole FROM 'C:/ITRLoader/DRole.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DAccessType FROM 'C:/ITRLoader/DAccessType.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DContributionType FROM 'C:/ITRLoader/DContributionType.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DRelationshipType FROM 'C:/ITRLoader/DRelationshipType.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DGroupType FROM 'C:/ITRLoader/DGroupType.txt' 
WITH (FIRSTROW = 2,  CODEPAGE = 'ACP');

BULK INSERT dbo.DRelationshipClass FROM 'C:/ITRLoader/DRelationshipClass.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DHandling0Definition FROM 'C:/ITRLoader/DHandling0Definition.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DHandlingStatus FROM 'C:/ITRLoader/DHandlingStatus.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DIncomeCurrency FROM 'C:/ITRLoader/DIncomeCurrency.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DPost FROM 'C:/ITRLoader/DPost.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DCitizenshipCountry FROM 'C:/ITRLoader/DCitizenshipCountry.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DEducation FROM 'C:/ITRLoader/DEducation.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DHandlingDefinition FROM 'C:/ITRLoader/DHandlingDefinition.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DIncome FROM 'C:/ITRLoader/DIncome.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DMaritalStatus FROM 'C:/ITRLoader/DMaritalStatus.txt' 
WITH (FIRSTROW = 2,  CODEPAGE = 'ACP');

BULK INSERT dbo.DOccupation FROM 'C:/ITRLoader/DOccupation.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DSeparateProperty FROM 'C:/ITRLoader/DSeparateProperty.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DSex FROM 'C:/ITRLoader/DSex.txt' 
WITH (FIRSTROW = 2, CODEPAGE = 'ACP');

BULK INSERT dbo.DTitle FROM 'C:/ITRLoader/DTitle.txt' 
WITH (FIRSTROW = 2,  CODEPAGE = 'ACP');

BULK INSERT dbo.DIdentificationType FROM 'C:/ITRLoader/DIdentificationType.txt' 
WITH (FIRSTROW = 2,  CODEPAGE = 'ACP');

BULK INSERT dbo.D0Alias FROM 'C:/ITRLoader/D0Alias.txt' 
WITH (FIRSTROW = 2,  CODEPAGE = 'ACP');

BULK INSERT dbo.DAlias FROM 'C:/ITRLoader/DAlias.txt' 
WITH (FIRSTROW = 2,  CODEPAGE = 'ACP');

BULK INSERT dbo.Pkd FROM 'C:/ITRLoader/Pkd.txt' 
WITH (FIRSTROW = 2,  CODEPAGE = 'ACP');

BULK INSERT dbo.DVoivodeship FROM 'C:/ITRLoader/DVoivodeship.txt' 
WITH (FIRSTROW = 2,  CODEPAGE = 'ACP');

--  Create Indexes 
ALTER TABLE AccessRestriction
	ADD CONSTRAINT UQ_AccessRestriction_AccessRestrictionID UNIQUE (AccessRestrictionID);

ALTER TABLE Customer
	ADD CONSTRAINT UQ_Customer_CustomerModulo UNIQUE (CustomerModulo);

ALTER TABLE Customer
	ADD CONSTRAINT UQ_Customer_CustomerID UNIQUE (CustomerID);

ALTER TABLE AddressList
	ADD CONSTRAINT UQ_AddressList_Adress UNIQUE (AdressID);

ALTER TABLE CustomerBranch
	ADD CONSTRAINT UQ_CustomerBranch_CustomerBranchID UNIQUE (CustomerBranchID);

ALTER TABLE Giodo
	ADD CONSTRAINT UQ_Giodo_GiodoID UNIQUE (GiodoID);

ALTER TABLE CustomerGroup
	ADD CONSTRAINT UQ_Group_GroupID UNIQUE (GroupID);

ALTER TABLE GroupMember
	ADD CONSTRAINT UQ_GroupMember_GroupMemberID UNIQUE (GroupMemberID);

ALTER TABLE Handling0
	ADD CONSTRAINT UQ_Handling0_Handling0ID UNIQUE (Handling0ID);

ALTER TABLE HandlingList
	ADD CONSTRAINT UQ_HandlingList_HandlingListID UNIQUE (HandlingListID);

ALTER TABLE IdentificationDoc
	ADD CONSTRAINT UQ_IdentificationDoc_IdentificationDocID UNIQUE (IdentificationDocID);

ALTER TABLE Individual
	ADD CONSTRAINT UQ_Individual_IndividualID UNIQUE (IndividualID);

ALTER TABLE Institutional
	ADD CONSTRAINT UQ_Institutional_InstitutionalID UNIQUE (InstitutionalID);

ALTER TABLE PredefCustomerList
	ADD CONSTRAINT UQ_PredefCustomerList_PredefAddressID UNIQUE (PredefAddressID);

ALTER TABLE CustomerDoc
	ADD CONSTRAINT UQ_CustomerDoc_DocumentID UNIQUE (DocumentID);

ALTER TABLE Blocade
	ADD CONSTRAINT UQ_Blocade_BlocadeID UNIQUE (BlocadeID);

ALTER TABLE Relationship
	ADD CONSTRAINT UQ_Relationship_RelationshipID UNIQUE (RelationshipID);

ALTER TABLE DAccountForm
	ADD CONSTRAINT UQ_DAccountForm_DAccountFormID UNIQUE (DAccountFormID);

ALTER TABLE DAMLCustomerType
	ADD CONSTRAINT UQ_DAMLCustomerType_DAMLCustomerTypeID UNIQUE (DAMLCustomerTypeID);

ALTER TABLE DCategory
	ADD CONSTRAINT UQ_DCategory_DCategoryID UNIQUE (DCategoryID);

ALTER TABLE DClaimsCategory
	ADD CONSTRAINT UQ_DClaimsCategory_DClaimsCategoryID UNIQUE (DClaimsCategoryID);

ALTER TABLE DConsentType
	ADD CONSTRAINT UQ_DConsentType_DConsentTypeID UNIQUE (DConsentTypeID);

ALTER TABLE DCustomerType
	ADD CONSTRAINT UQ_DCustomerType_DCustomerTypeID UNIQUE (DCustomerTypeID);

ALTER TABLE DForm
	ADD CONSTRAINT UQ_DForm_DFormID UNIQUE (DFormID);

ALTER TABLE DInvestmentRiskProfile
	ADD CONSTRAINT UQ_DInvestmentRiskProfile_DInvestmentRiskProfileID UNIQUE (DInvestmentRiskProfileID);

ALTER TABLE DMIFID
	ADD CONSTRAINT UQ_DMIFID_DMIFIDID UNIQUE (DMIFIDID);

ALTER TABLE DNBPType
	ADD CONSTRAINT UQ_DNBPType_DNBPTypeID UNIQUE (DNBPTypeID);

ALTER TABLE DParticularForm
	ADD CONSTRAINT UQ_DParticularForm_DParticularFormID UNIQUE (DParticularFormID);

ALTER TABLE DPKD
	ADD CONSTRAINT UQ_DPKD_DPKDID UNIQUE (DPKDID);

ALTER TABLE DRating
	ADD CONSTRAINT UQ_DRating_DRatingID UNIQUE (DRatingID);

ALTER TABLE DRiskGroup
	ADD CONSTRAINT UQ_DRiskGroup_DRiskGroupID UNIQUE (DRiskGroupID);

ALTER TABLE DSegment
	ADD CONSTRAINT UQ_DSegment_DSegmentID UNIQUE (DSegmentID);

ALTER TABLE Dictionary
	ADD CONSTRAINT UQ_Dictionary_DictionaryID UNIQUE (DictionaryID);

ALTER TABLE DEntity
	ADD CONSTRAINT UQ_DEntity_DEntityID UNIQUE (DEntityID);

ALTER TABLE DRole
	ADD CONSTRAINT UQ_DRole_DRoleID UNIQUE (DRoleID);

ALTER TABLE DAccessType
	ADD CONSTRAINT UQ_DAccessType_DAccessTypeID UNIQUE (DAccessTypeID);

ALTER TABLE DContributionType
	ADD CONSTRAINT UQ_DContributionType_DContributionTypeID UNIQUE (DContributionTypeID);

ALTER TABLE DRelationshipType
	ADD CONSTRAINT UQ_DRelationshipType_DRelationshipTypeID UNIQUE (DRelationshipTypeID);

ALTER TABLE DGroupType
	ADD CONSTRAINT UQ_DGroupType_DGroupTypeID UNIQUE (DGroupTypeID);

ALTER TABLE DRelationshipClass
	ADD CONSTRAINT UQ_DRelationshipClass_DRelationshipClassID UNIQUE (DRelationshipClassID);

ALTER TABLE DHandling0Definition
	ADD CONSTRAINT UQ_DHandling0Definition_DHandling0DefinitionID UNIQUE (DHandling0DefinitionID);

ALTER TABLE DHandlingStatus
	ADD CONSTRAINT UQ_DHandlingStatus_DHandlingStatusID UNIQUE (DHandlingStatusID);

ALTER TABLE DIncomeCurrency
	ADD CONSTRAINT UQ_DIncomeCurrency_DIncomeCurrencyID UNIQUE (DIncomeCurrencyID);

ALTER TABLE DPost
	ADD CONSTRAINT UQ_DPost_DPostID UNIQUE (DPostID);

ALTER TABLE DCitizenshipCountry
	ADD CONSTRAINT UQ_DCitizenshipCountry_DCitizenshipCountryID UNIQUE (DCitizenshipCountryID);

ALTER TABLE DEducation
	ADD CONSTRAINT UQ_DEducation_DEducationID UNIQUE (DEducationID);

ALTER TABLE DHandlingDefinition
	ADD CONSTRAINT UQ_DHandlingDefinition_DHandlingDefinitionID UNIQUE (DHandlingDefinitionID);

ALTER TABLE DIncome
	ADD CONSTRAINT UQ_DIncome_DIncomeID UNIQUE (DIncomeID);

ALTER TABLE DMaritalStatus
	ADD CONSTRAINT UQ_DMaritalStatus_DMaritalStatusID UNIQUE (DMaritalStatusID);

ALTER TABLE DOccupation
	ADD CONSTRAINT UQ_DOccupation_DOccupationID UNIQUE (DOccupationID);

ALTER TABLE DSeparateProperty
	ADD CONSTRAINT UQ_DSeparateProperty_DSeparatePropertyID UNIQUE (DSeparatePropertyID);

ALTER TABLE DAddressType
	ADD CONSTRAINT UQ_DAddressType_DAddressTypeID UNIQUE (DAddressTypeID);

ALTER TABLE DVoivodeship
	ADD CONSTRAINT UQ_DVoivodeship_DVoivodeshipID UNIQUE (DVoivodeshipID);

ALTER TABLE DSex
	ADD CONSTRAINT UQ_DSex_DSexID UNIQUE (DSexID);

ALTER TABLE DTitle
	ADD CONSTRAINT UQ_DTitle_DTitleID UNIQUE (DTitleID);

ALTER TABLE DIdentificationType
	ADD CONSTRAINT UQ_DIdentificationType_DIdentificationTypeID UNIQUE (DIdentificationTypeID);

ALTER TABLE D0Alias
	ADD CONSTRAINT UQ_D0Alias_D0AliasID UNIQUE (D0AliasID);

ALTER TABLE DAlias
	ADD CONSTRAINT UQ_DAliases_DAliasID UNIQUE (DAliasID);

ALTER TABLE Pkd
	ADD CONSTRAINT UQ_Pkd_PkdID UNIQUE (PkdID);

--  Create Primary Key Constraints 
ALTER TABLE AccessRestriction ADD CONSTRAINT PK_AccessRestriction 
	PRIMARY KEY CLUSTERED (AccessRestrictionID);

ALTER TABLE Customer ADD CONSTRAINT PK_Customer 
	PRIMARY KEY CLUSTERED (CustomerID);

ALTER TABLE AddressList ADD CONSTRAINT PK_AddressList 
	PRIMARY KEY CLUSTERED (AdressID);

ALTER TABLE CustomerBranch ADD CONSTRAINT PK_CustomerBranch 
	PRIMARY KEY CLUSTERED (CustomerBranchID);

ALTER TABLE Giodo ADD CONSTRAINT PK_Giodo 
	PRIMARY KEY CLUSTERED (GiodoID);

ALTER TABLE CustomerGroup ADD CONSTRAINT PK_Group 
	PRIMARY KEY CLUSTERED (GroupID);

ALTER TABLE GroupMember ADD CONSTRAINT PK_GroupMember 
	PRIMARY KEY CLUSTERED (GroupMemberID);

ALTER TABLE Handling0 ADD CONSTRAINT PK_Handling0 
	PRIMARY KEY CLUSTERED (Handling0ID);

ALTER TABLE HandlingList ADD CONSTRAINT PK_HandlingList 
	PRIMARY KEY CLUSTERED (HandlingListID);

ALTER TABLE IdentificationDoc ADD CONSTRAINT PK_IdentificationDoc 
	PRIMARY KEY CLUSTERED (IdentificationDocID);

ALTER TABLE Individual ADD CONSTRAINT PK_Individual 
	PRIMARY KEY CLUSTERED (IndividualID);

ALTER TABLE Institutional ADD CONSTRAINT PK_InstitutionalID 
	PRIMARY KEY CLUSTERED (InstitutionalID);

ALTER TABLE PredefCustomerList ADD CONSTRAINT PK_PredefCustomerList 
	PRIMARY KEY CLUSTERED (PredefAddressID);

ALTER TABLE CustomerDoc ADD CONSTRAINT PK_CustomerDoc 
	PRIMARY KEY CLUSTERED (DocumentID);

ALTER TABLE Blocade ADD CONSTRAINT PK_Blocade 
	PRIMARY KEY CLUSTERED (BlocadeID);

ALTER TABLE Relationship ADD CONSTRAINT PK_Relationship 
	PRIMARY KEY CLUSTERED (RelationshipID);

ALTER TABLE DAccountForm ADD CONSTRAINT PK_DAccountForm 
	PRIMARY KEY CLUSTERED (DAccountFormID);

ALTER TABLE DAMLCustomerType ADD CONSTRAINT PK_DAMLCustomerType 
	PRIMARY KEY CLUSTERED (DAMLCustomerTypeID);

ALTER TABLE DCategory ADD CONSTRAINT PK_DCategory 
	PRIMARY KEY CLUSTERED (DCategoryID);

ALTER TABLE DClaimsCategory ADD CONSTRAINT PK_DClaimsCategory 
	PRIMARY KEY CLUSTERED (DClaimsCategoryID);

ALTER TABLE DConsentType ADD CONSTRAINT PK_DConsentType 
	PRIMARY KEY CLUSTERED (DConsentTypeID);

ALTER TABLE DCustomerType ADD CONSTRAINT PK_DCustomerType 
	PRIMARY KEY CLUSTERED (DCustomerTypeID);

ALTER TABLE DForm ADD CONSTRAINT PK_DForm 
	PRIMARY KEY CLUSTERED (DFormID);

ALTER TABLE DInvestmentRiskProfile ADD CONSTRAINT PK_DInvestmentRiskProfile 
	PRIMARY KEY CLUSTERED (DInvestmentRiskProfileID);

ALTER TABLE DMIFID ADD CONSTRAINT PK_DMIFID 
	PRIMARY KEY CLUSTERED (DMIFIDID);

ALTER TABLE DNBPType ADD CONSTRAINT PK_DNBPType 
	PRIMARY KEY CLUSTERED (DNBPTypeID);

ALTER TABLE DParticularForm ADD CONSTRAINT PK_DParticularForm 
	PRIMARY KEY CLUSTERED (DParticularFormID);

ALTER TABLE DPKD ADD CONSTRAINT PK_DPKD 
	PRIMARY KEY CLUSTERED (DPKDID);

ALTER TABLE DRating ADD CONSTRAINT PK_DRating 
	PRIMARY KEY CLUSTERED (DRatingID);

ALTER TABLE DRiskGroup ADD CONSTRAINT PK_DRiskGroup 
	PRIMARY KEY CLUSTERED (DRiskGroupID);

ALTER TABLE DSegment ADD CONSTRAINT PK_DSegment 
	PRIMARY KEY CLUSTERED (DSegmentID);

ALTER TABLE Dictionary ADD CONSTRAINT PK_Dictionary 
	PRIMARY KEY CLUSTERED (DictionaryID);

ALTER TABLE DEntity ADD CONSTRAINT PK_DEntity 
	PRIMARY KEY CLUSTERED (DEntityID);

ALTER TABLE DRole ADD CONSTRAINT PK_DRole 
	PRIMARY KEY CLUSTERED (DRoleID);

ALTER TABLE DAccessType ADD CONSTRAINT PK_DAccessType 
	PRIMARY KEY CLUSTERED (DAccessTypeID);

ALTER TABLE DContributionType ADD CONSTRAINT PK_DContributionType 
	PRIMARY KEY CLUSTERED (DContributionTypeID);

ALTER TABLE DRelationshipType ADD CONSTRAINT PK_DRelationshipType 
	PRIMARY KEY CLUSTERED (DRelationshipTypeID);

ALTER TABLE DGroupType ADD CONSTRAINT PK_DGroupType 
	PRIMARY KEY CLUSTERED (DGroupTypeID);

ALTER TABLE DRelationshipClass ADD CONSTRAINT PK_DRelationshipClass 
	PRIMARY KEY CLUSTERED (DRelationshipClassID);

ALTER TABLE DHandling0Definition ADD CONSTRAINT PK_DHandling0Definition 
	PRIMARY KEY CLUSTERED (DHandling0DefinitionID);

ALTER TABLE DHandlingStatus ADD CONSTRAINT PK_DHandlingStatus 
	PRIMARY KEY CLUSTERED (DHandlingStatusID);

ALTER TABLE DIncomeCurrency ADD CONSTRAINT PK_DIncomeCurrency 
	PRIMARY KEY CLUSTERED (DIncomeCurrencyID);

ALTER TABLE DPost ADD CONSTRAINT PK_DPost 
	PRIMARY KEY CLUSTERED (DPostID);

ALTER TABLE DCitizenshipCountry ADD CONSTRAINT PK_DCitizenshipCountry 
	PRIMARY KEY CLUSTERED (DCitizenshipCountryID);

ALTER TABLE DEducation ADD CONSTRAINT PK_DEducation 
	PRIMARY KEY CLUSTERED (DEducationID);

ALTER TABLE DHandlingDefinition ADD CONSTRAINT PK_DHandlingDefinition 
	PRIMARY KEY CLUSTERED (DHandlingDefinitionID);

ALTER TABLE DIncome ADD CONSTRAINT PK_DIncome 
	PRIMARY KEY CLUSTERED (DIncomeID);

ALTER TABLE DMaritalStatus ADD CONSTRAINT PK_DMaritalStatus 
	PRIMARY KEY CLUSTERED (DMaritalStatusID);

ALTER TABLE DOccupation ADD CONSTRAINT PK_DOccupation 
	PRIMARY KEY CLUSTERED (DOccupationID);

ALTER TABLE DSeparateProperty ADD CONSTRAINT PK_DSeparateProperty 
	PRIMARY KEY CLUSTERED (DSeparatePropertyID);

ALTER TABLE DAddressType ADD CONSTRAINT PK_DAddressType 
	PRIMARY KEY CLUSTERED (DAddressTypeID);

ALTER TABLE DVoivodeship ADD CONSTRAINT PK_DVoivodeship 
	PRIMARY KEY CLUSTERED (DVoivodeshipID);

ALTER TABLE DSex ADD CONSTRAINT PK_DSex 
	PRIMARY KEY CLUSTERED (DSexID);

ALTER TABLE DTitle ADD CONSTRAINT PK_DTitle 
	PRIMARY KEY CLUSTERED (DTitleID);

ALTER TABLE DIdentificationType ADD CONSTRAINT PK_DIdentificationType 
	PRIMARY KEY CLUSTERED (DIdentificationTypeID);

ALTER TABLE D0Alias ADD CONSTRAINT PK_DAliases 
	PRIMARY KEY CLUSTERED (D0AliasID);

ALTER TABLE DAlias ADD CONSTRAINT PK_DAlias 
	PRIMARY KEY CLUSTERED (DAliasID);

ALTER TABLE Pkd ADD CONSTRAINT PK_Pkd 
	PRIMARY KEY CLUSTERED (PkdID);



--  Create Foreign Key Constraints 
ALTER TABLE AccessRestriction ADD CONSTRAINT FK_ARCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE AccessRestriction ADD CONSTRAINT FK_AccessRestriction_DRole 
	FOREIGN KEY (Role) REFERENCES DRole (DRoleID);

ALTER TABLE AccessRestriction ADD CONSTRAINT FK_AccessRestriction_DAccessType 
	FOREIGN KEY (AccessType) REFERENCES DAccessType (DAccessTypeID);

ALTER TABLE Customer ADD CONSTRAINT FK_Customer_DCategory 
	FOREIGN KEY (Category) REFERENCES DCategory (DCategoryID);

ALTER TABLE Customer ADD CONSTRAINT FK_Customer_DForm 
	FOREIGN KEY (Form) REFERENCES DForm (DFormID);

ALTER TABLE Customer ADD CONSTRAINT FK_Customer_DParticularForm 
	FOREIGN KEY (ParticularForm) REFERENCES DParticularForm (DParticularFormID);

ALTER TABLE Customer ADD CONSTRAINT FK_Customer_DCustomerType 
	FOREIGN KEY (Type) REFERENCES DCustomerType (DCustomerTypeID);

ALTER TABLE Customer ADD CONSTRAINT FK_Customer_NBPType 
	FOREIGN KEY (NBPType) REFERENCES DNBPType (DNBPTypeID);

ALTER TABLE Customer ADD CONSTRAINT FK_Customer_DSegment 
	FOREIGN KEY (Segment) REFERENCES DSegment (DSegmentID);

ALTER TABLE AddressList ADD CONSTRAINT FK_AdressList_Customer 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE AddressList ADD CONSTRAINT FK_AddressList_AddressType 
	FOREIGN KEY (AddressType) REFERENCES DAddressType (DAddressTypeID);

ALTER TABLE AddressList ADD CONSTRAINT FK_AddressList_DCitizenshipCountry 
	FOREIGN KEY (AddressCountry) REFERENCES DCitizenshipCountry (DCitizenshipCountryID);

ALTER TABLE AddressList ADD CONSTRAINT FK_AddressList_DVoivodeship 
	FOREIGN KEY (Voivodeship) REFERENCES DVoivodeship (DVoivodeshipID);

ALTER TABLE CustomerBranch ADD CONSTRAINT FK_CBCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE CustomerBranch ADD CONSTRAINT FK_CustomerBranch_DEntity 
	FOREIGN KEY (Entity) REFERENCES DEntity (DEntityID);

ALTER TABLE Giodo ADD CONSTRAINT FK_GCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE Giodo ADD CONSTRAINT FK_Giodo_DConsentType 
	FOREIGN KEY (ConsentType) REFERENCES DConsentType (DConsentTypeID);

ALTER TABLE CustomerGroup ADD CONSTRAINT FK_CustomerGroup_DGroupType 
	FOREIGN KEY (Type) REFERENCES DGroupType (DGroupTypeID);

ALTER TABLE GroupMember ADD CONSTRAINT FK_GroupID 
	FOREIGN KEY (GroupID) REFERENCES CustomerGroup (GroupID);

ALTER TABLE GroupMember ADD CONSTRAINT FK_GMCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID)
	ON UPDATE CASCADE;

ALTER TABLE GroupMember ADD CONSTRAINT FK_GroupMember_DContributionType 
	FOREIGN KEY (ContributionType) REFERENCES DContributionType (DContributionTypeID);

ALTER TABLE GroupMember ADD CONSTRAINT FK_GroupMember_DRelationshipClass 
	FOREIGN KEY (RelationshipClass) REFERENCES DRelationshipClass (DRelationshipClassID);

ALTER TABLE Handling0 ADD CONSTRAINT FK_HCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE Handling0 ADD CONSTRAINT FK_Handling0_DHandling0Definition 
	FOREIGN KEY (Handling0) REFERENCES DHandling0Definition (DHandling0DefinitionID);

ALTER TABLE HandlingList ADD CONSTRAINT FK_Handling0ID 
	FOREIGN KEY (Handling0ID) REFERENCES Handling0 (Handling0ID);

ALTER TABLE HandlingList ADD CONSTRAINT FK_HandlingList_DHandlingDefinition 
	FOREIGN KEY (Handling) REFERENCES DHandlingDefinition (DHandlingDefinitionID);

ALTER TABLE HandlingList ADD CONSTRAINT FK_HandlingList_DHandlingStatus 
	FOREIGN KEY (Status) REFERENCES DHandlingStatus (DHandlingStatusID);

ALTER TABLE IdentificationDoc ADD CONSTRAINT FK_IndividualID 
	FOREIGN KEY (IndividualID) REFERENCES Individual (IndividualID);

ALTER TABLE IdentificationDoc ADD CONSTRAINT FK_IdentificationDoc_DIdentificationType 
	FOREIGN KEY (IdentificationType) REFERENCES DIdentificationType (DIdentificationTypeID);

ALTER TABLE Individual ADD CONSTRAINT FK_IdCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_DTitle 
	FOREIGN KEY (Title) REFERENCES DTitle (DTitleID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_DCitizenshipCountry 
	FOREIGN KEY (Citizenship) REFERENCES DCitizenshipCountry (DCitizenshipCountryID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_DSex 
	FOREIGN KEY (Sex) REFERENCES DSex (DSexID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_MaritalStatus 
	FOREIGN KEY (MaritalStatus) REFERENCES DMaritalStatus (DMaritalStatusID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_DEducation 
	FOREIGN KEY (Education) REFERENCES DEducation (DEducationID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_DOccupation 
	FOREIGN KEY (Occupation) REFERENCES DOccupation (DOccupationID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_DIncome 
	FOREIGN KEY (Income) REFERENCES DIncome (DIncomeID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_DPost 
	FOREIGN KEY (Post) REFERENCES DPost (DPostID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_DIncomeCurrency 
	FOREIGN KEY (IncomeCurrency) REFERENCES DIncomeCurrency (DIncomeCurrencyID);

ALTER TABLE Individual ADD CONSTRAINT FK_Individual_DSeperateProperty 
	FOREIGN KEY (SeparateProperty) REFERENCES DSeparateProperty (DSeparatePropertyID);

ALTER TABLE Institutional ADD CONSTRAINT FK_InCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE Institutional ADD CONSTRAINT FK_Inistitutional_DAccountForm 
	FOREIGN KEY (AccountingForm) REFERENCES DAccountForm (DAccountFormID);

ALTER TABLE Institutional ADD CONSTRAINT FK_Institutional_DMIFID 
	FOREIGN KEY (Mifid) REFERENCES DMIFID (DMIFIDID);

ALTER TABLE Institutional ADD CONSTRAINT FK_Institutional_DClaimsCategory 
	FOREIGN KEY (DueCategory) REFERENCES DClaimsCategory (DClaimsCategoryID);

ALTER TABLE Institutional ADD CONSTRAINT FK_Institutional_DRating 
	FOREIGN KEY (CustomerRating) REFERENCES DRating (DRatingID);

ALTER TABLE Institutional ADD CONSTRAINT FK_Institutional_DInvestmentRiskProfile 
	FOREIGN KEY (InvestmentRiskProfile) REFERENCES DInvestmentRiskProfile (DInvestmentRiskProfileID);

ALTER TABLE Institutional ADD CONSTRAINT FK_Institutional_DRiskGroup 
	FOREIGN KEY (RiskGroup) REFERENCES DRiskGroup (DRiskGroupID);

ALTER TABLE PredefCustomerList ADD CONSTRAINT FK_PCLCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE CustomerDoc ADD CONSTRAINT FK_CdCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE Blocade ADD CONSTRAINT FK_BCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE Relationship ADD CONSTRAINT FK_RCustomerID 
	FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE Relationship ADD CONSTRAINT FK_Relationship_DRelationshipType 
	FOREIGN KEY (RelationshipType) REFERENCES DRelationshipType (DRelationshipTypeID);

ALTER TABLE Relationship ADD CONSTRAINT FK_Relationship_CustomerID 
	FOREIGN KEY (RelationshipCustomerID) REFERENCES Customer (CustomerID);

ALTER TABLE DAccountForm ADD CONSTRAINT FK_DAccount_Form_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DAMLCustomerType ADD CONSTRAINT FK_DAMLCustomerType_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DCategory ADD CONSTRAINT FK_DCategory 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DClaimsCategory ADD CONSTRAINT FK_DClaimsCategory_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DConsentType ADD CONSTRAINT FK_DConsentType 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DCustomerType ADD CONSTRAINT FK_DCustomerType 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DForm ADD CONSTRAINT FK_DForm 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DInvestmentRiskProfile ADD CONSTRAINT FK_DRiskInvestmentProfile_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DMIFID ADD CONSTRAINT FK_DMIFID_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DNBPType ADD CONSTRAINT FK_DNBPType 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DParticularForm ADD CONSTRAINT FK_DParticularForm 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DPKD ADD CONSTRAINT FK_DPKD_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DRating ADD CONSTRAINT FK_DRating_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DRiskGroup ADD CONSTRAINT FK_DRiskGroup_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DSegment ADD CONSTRAINT FK_DSegment_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DEntity ADD CONSTRAINT FK_DEntity_Dictionary 
	FOREIGN KEY (DctionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DRole ADD CONSTRAINT FK_DRole_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DAccessType ADD CONSTRAINT FK_DAT_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DContributionType ADD CONSTRAINT FK_DCT_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DRelationshipType ADD CONSTRAINT FK_DRT_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DGroupType ADD CONSTRAINT FK_DGT_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DRelationshipClass ADD CONSTRAINT FK_DRC_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DHandling0Definition ADD CONSTRAINT FK_DH0D_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DHandlingStatus ADD CONSTRAINT FK_DHS_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DIncomeCurrency ADD CONSTRAINT FK_DIC_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DPost ADD CONSTRAINT FK_DP_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DCitizenshipCountry ADD CONSTRAINT FK_DCC_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DEducation ADD CONSTRAINT FK_DE_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DHandlingDefinition ADD CONSTRAINT FK_DHD_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DIncome ADD CONSTRAINT FK_DI_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DMaritalStatus ADD CONSTRAINT FK_DMS_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DOccupation ADD CONSTRAINT FK_DO_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DSeparateProperty ADD CONSTRAINT FK_DSP_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DAddressType ADD CONSTRAINT FK_DAddressType_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DVoivodeship ADD CONSTRAINT FK_DVoivodeship_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DSex ADD CONSTRAINT FK_DS_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DTitle ADD CONSTRAINT FK_DT_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DIdentificationType ADD CONSTRAINT FK_DIdT_Dictionary 
	FOREIGN KEY (DictionaryID) REFERENCES Dictionary (DictionaryID);

ALTER TABLE DAlias ADD CONSTRAINT FK_DAlias_D0Alias 
	FOREIGN KEY (D0AliasID) REFERENCES D0Alias (D0AliasID);









EXEC sp_addextendedproperty 'MS_Description', 'Definicje praw dostêpu do danych klienta. ', 'Schema', dbo, 'table', AccessRestriction;



EXEC sp_addextendedproperty 'MS_Description', 'DRole
1. Doradca
2. Dyrektor oddzia³u
3. Kierownik placówki
4. Naczelnik
5. Kasjer
6. Skarbnik
7. Pracownik zaplecza', 'Schema', dbo, 'table', AccessRestriction, 'column', Role;

EXEC sp_addextendedproperty 'MS_Description', 'DEntity
199999 Dowolny oddzia³
100000 Centrala
200000 Oddzia³ MPK Klienta
3RRxxx Oddzia³ xxx w regionie RR
4RR000 Oddzia³y w ramach regionu', 'Schema', dbo, 'table', AccessRestriction, 'column', EntityAccessRestriction;

EXEC sp_addextendedproperty 'MS_Description', 'DAccessType
1. Pe³ny dostêp
2. Tylko operacje bez widocznoœci danych wra¿liwych (w tym pracownicy banku)', 'Schema', dbo, 'table', AccessRestriction, 'column', AccessType;



EXEC sp_addextendedproperty 'MS_Description', 'Podstawowa kartoteka klienta. Ta tablica jest dla wszystkich klientów.

Modu³y obs³ugi:
Za³o¿enie - CustomerFoundation
Modyfikacja - CustomerModification
Usuniêcie - CustomerDeletion', 'Schema', dbo, 'table', Customer;

EXEC sp_addextendedproperty 'MS_Description', 'Algorytm Luhna', 'Schema', dbo, 'table', Customer, 'column', CustomerModulo;

EXEC sp_addextendedproperty 'MS_Description', 'DCategory
0. klient potencjalny
1. klient rzeczywisy', 'Schema', dbo, 'table', Customer, 'column', Category;




EXEC sp_addextendedproperty 'MS_Description', 'DForm
1. Osoba prawna
2. Jednostka organizacyjna niemaj¹ca osobowoœci prawnej
3. Osoba fizyczna prowadz¹ca dzia³alnoœæ gospodarcz¹', 'Schema', dbo, 'table', Customer, 'column', Form;

EXEC sp_addextendedproperty 'MS_Description', 'DParticularForm
Lista dla Finrep i Corep', 'Schema', dbo, 'table', Customer, 'column', ParticularForm;

EXEC sp_addextendedproperty 'MS_Description', 'DCustomerType
1. pojedynczy
2. zbiorowy', 'Schema', dbo, 'table', Customer, 'column', Type;

EXEC sp_addextendedproperty 'MS_Description', 'DNBPType
Wg zestawienia dla NBP', 'Schema', dbo, 'table', Customer, 'column', NBPType;

EXEC sp_addextendedproperty 'MS_Description', 'DSegment
1. indywidualny
2. rolnik
3. podmiot gospodarczy
4. gospodarstwo rolne
5. bank grupy BPS', 'Schema', dbo, 'table', Customer, 'column', Segment;

EXEC sp_addextendedproperty 'MS_Description', 'DTakNie', 'Schema', dbo, 'table', Customer, 'column', ResidenceStatus;

EXEC sp_addextendedproperty 'MS_Description', 'DResidenceCountry', 'Schema', dbo, 'table', Customer, 'column', ResidenceCountry;


EXEC sp_addextendedproperty 'MS_Description', 'DResidenceCountry', 'Schema', dbo, 'table', Customer, 'column', TaxResidenceCountry;

EXEC sp_addextendedproperty 'MS_Description', 'DAMLCustomerType', 'Schema', dbo, 'table', Customer, 'column', AMLCustomerType;

EXEC sp_addextendedproperty 'MS_Description', 'DTakNie', 'Schema', dbo, 'table', Customer, 'column', WithholdingInterestTax;

EXEC sp_addextendedproperty 'MS_Description', 'DTakNie', 'Schema', dbo, 'table', Customer, 'column', TaxExemptionScheme;





EXEC sp_addextendedproperty 'MS_Description', 'Lista adresów klienta. Obowi¹zkowy jest adres sta³y i co najmniej jeden adres korespondencyjny. W liœcie adresów mog¹ byæ zdefiniowane równie¿ adresy e-mail i numery telefonów do komunikacji za pomoca SMS.', 'Schema', dbo, 'table', AddressList;


EXEC sp_addextendedproperty 'MS_Description', 'DStatus
0. nieaktywny
1. aktywny', 'Schema', dbo, 'table', AddressList, 'column', Status;

EXEC sp_addextendedproperty 'MS_Description', 'DAddressType
0. sta³y
1. korespondencyjny
2. e-mail
3. nr telefonu SMS
4. nr jednostki organizacyjnej banku
5. SWIFT
6. Telefon domowy
7. Telefon s³u¿bowy
8. Telefon komórkowy
9. Fax
10. Telex', 'Schema', dbo, 'table', AddressList, 'column', AddressType;

EXEC sp_addextendedproperty 'MS_Description', '  ', 'Schema', dbo, 'table', AddressList, 'column', AddressName;






EXEC sp_addextendedproperty 'MS_Description', 'DVoivodeship
Tabela województw', 'Schema', dbo, 'table', AddressList, 'column', Voivodeship;


EXEC sp_addextendedproperty 'MS_Description', 'DCitizenshipCountry', 'Schema', dbo, 'table', AddressList, 'column', AddressCountry;



EXEC sp_addextendedproperty 'MS_Description', 'Lista oddzia³ów, doradców, do których nale¿y klient. Dla "starych" klientów mo¿e wyst¹piæ równie¿ dotychczasowe modulo Klienta, w sytuacjach, gdy klient mia³ kilka kartotek.', 'Schema', dbo, 'table', CustomerBranch;


EXEC sp_addextendedproperty 'MS_Description', 'Modulo10 Algorytm Luhna', 'Schema', dbo, 'table', CustomerBranch, 'column', HistoricalModulo;


EXEC sp_addextendedproperty 'MS_Description', 'Dane z EmployeeList', 'Schema', dbo, 'table', CustomerBranch, 'column', ConsultantID;


EXEC sp_addextendedproperty 'MS_Description', 'Tablica zgód zwi¹zanych z ochron¹ danych osobowych sk³¹danych przez klienta i okreœlaj¹cych zachowanie banku wobec klienta w kontekœcie Ustawy o ochronie danych osobowych.', 'Schema', dbo, 'table', Giodo;


EXEC sp_addextendedproperty 'MS_Description', 'DConsentType
0. Zgoda na przechowywanie i przetwarzanie danych osobowych
1. Zgoda na marketing produktów Banku
2. Zgoda na przetwarzanie danych osobowych w celach marketingowych w ramach Banku
3. Zgoda na otrzymywanie korespondencji drog¹ elektroniczn¹
4. Zgoda na profilowanie klienta', 'Schema', dbo, 'table', Giodo, 'column', ConsentType;



EXEC sp_addextendedproperty 'MS_Description', 'Definicja grupy w tym nazwa, grupy i typ grupy. ', 'Schema', dbo, 'table', CustomerGroup;


EXEC sp_addextendedproperty 'MS_Description', 'DGroupeType', 'Schema', dbo, 'table', CustomerGroup, 'column', Type;



EXEC sp_addextendedproperty 'MS_Description', 'Opis klienta jako cz³onka Grupy (kapita³owej, organizacyjnej itp). Ka¿dy klient mo¿e nale¿eæ do wielu grup. W tablicy okreœlony jest udzia³ kwotowy albo procentowy, o ile wystêpuj¹.', 'Schema', dbo, 'table', GroupMember;



EXEC sp_addextendedproperty 'MS_Description', 'DContributionType', 'Schema', dbo, 'table', GroupMember, 'column', ContributionType;



EXEC sp_addextendedproperty 'MS_Description', 'DRelationshipClass
1. Klient grupowy
2. Grupa kapita³owa
3. Powi¹zania kapita³owe
4. Powi¹zania organizacyjne
5. Powi¹zania gospodarcze
6. Powi¹zania personalne
7. Wspólnota maj¹tkowa
8. Upowa¿nienie
9. W³aœcicielskie
10. Beneficjent rzeczywisty
11. Grupa finansowa
12. Akcjonariusz', 'Schema', dbo, 'table', GroupMember, 'column', RelationshipClass;

EXEC sp_addextendedproperty 'MS_Description', 'Tablica unikalna dla ka¿dego klienta. Jest kopi¹ tablicy Handling0Template dla danego segmentu klienta uzupe³nion¹ o umowê ramow¹, dataê uruchomienia obs³ugi. Do Handling0 pod³¹czona jest lista obs³ug szczegó³owych (Handling)', 'Schema', dbo, 'table', Handling0;

EXEC sp_addextendedproperty 'MS_Description', 'DHandling0Definition', 'Schema', dbo, 'table', Handling0, 'column', Handling0;


EXEC sp_addextendedproperty 'MS_Description', 'DAgreementTemplate', 'Schema', dbo, 'table', Handling0, 'column', FrameAgreementTemplate;



EXEC sp_addextendedproperty 'MS_Description', 'DTerminationType
0. trwa
1. terminowo
2. zerwanie przez klienta
3. zerwanie przez bank', 'Schema', dbo, 'table', Handling0, 'column', TerminationType;


EXEC sp_addextendedproperty 'MS_Description', 'HandlingList jest list¹ aktywowanych obs³ug klienta.', 'Schema', dbo, 'table', HandlingList;


EXEC sp_addextendedproperty 'MS_Description', 'DHandlingDefinition', 'Schema', dbo, 'table', HandlingList, 'column', Handling;

EXEC sp_addextendedproperty 'MS_Description', 'DTakNie', 'Schema', dbo, 'table', HandlingList, 'column', Stability;

EXEC sp_addextendedproperty 'MS_Description', 'DHandlingStatus
0. Oferowana
1. Za³o¿ona
2. Zakoñczona', 'Schema', dbo, 'table', HandlingList, 'column', Status;


EXEC sp_addextendedproperty 'MS_Description', 'Lista dokumentów to¿samoœci klienta. Tylko dla klientów indywidualnych.', 'Schema', dbo, 'table', IdentificationDoc;


EXEC sp_addextendedproperty 'MS_Description', 'DIdentification
1. dowód osobisty
2. paszport polski
3. dowód osobosty zagraniczny
4. paszport zagraniczny
5. Legitymacja ucznioska/studencka', 'Schema', dbo, 'table', IdentificationDoc, 'column', IdentificationType;



EXEC sp_addextendedproperty 'MS_Description', 'Tablica zawiera dane charakteryzuj¹ce klienta indywidualnego. Stanowi uzupe³nienie tablicy Customer.', 'Schema', dbo, 'table', Individual;






EXEC sp_addextendedproperty 'MS_Description', 'DTakNie', 'Schema', dbo, 'table', Individual, 'column', Minor;

EXEC sp_addextendedproperty 'MS_Description', 'DTakNie', 'Schema', dbo, 'table', Individual, 'column', Incapacitated;

EXEC sp_addextendedproperty 'MS_Description', 'DTitle
1. Pan
2. Pani
3. [         ]   {blank}', 'Schema', dbo, 'table', Individual, 'column', Title;

EXEC sp_addextendedproperty 'MS_Description', '1 = zmar³a', 'Schema', dbo, 'table', Individual, 'column', DeathCheck;


EXEC sp_addextendedproperty 'MS_Description', 'DCitizenshipCountry', 'Schema', dbo, 'table', Individual, 'column', Citizenship;



EXEC sp_addextendedproperty 'MS_Description', 'DSex', 'Schema', dbo, 'table', Individual, 'column', Sex;

EXEC sp_addextendedproperty 'MS_Description', 'DMaritalStatus
1. panna/kawaler
2. ¿onaty/mê¿atka
3. kohabitacja
4. separacja
5. rozwiedziony/rozwiedziona
6. wdowiec/wdowa
7. pozosta³e
8. nieznane', 'Schema', dbo, 'table', Individual, 'column', MaritalStatus;

EXEC sp_addextendedproperty 'MS_Description', 'DEducation
0. niepe³ne i podstawowe
1. zasadnicze zawodowe
2. œrednie
3. pomaturalne
4. wy¿sze (licencjat i in¿ynier)
5. wy¿sze magisterskie
6. podyplomowe
7. inne
8. nieznane', 'Schema', dbo, 'table', Individual, 'column', Education;

EXEC sp_addextendedproperty 'MS_Description', 'DOccupation
Uk³ad s³ownika zgodny z BIK', 'Schema', dbo, 'table', Individual, 'column', Occupation;

EXEC sp_addextendedproperty 'MS_Description', 'DIncome
Uk³ad s³ownika dla BIK', 'Schema', dbo, 'table', Individual, 'column', Income;



EXEC sp_addextendedproperty 'MS_Description', 'DPost
Uk³ad ze s³ownika DD', 'Schema', dbo, 'table', Individual, 'column', Post;


EXEC sp_addextendedproperty 'MS_Description', '>=0', 'Schema', dbo, 'table', Individual, 'column', ChildrenNumber;

EXEC sp_addextendedproperty 'MS_Description', '>=0', 'Schema', dbo, 'table', Individual, 'column', DependentsNumber;


EXEC sp_addextendedproperty 'MS_Description', 'DIncomeCurrency
Numeracja zgodna z ISO', 'Schema', dbo, 'table', Individual, 'column', IncomeCurrency;

EXEC sp_addextendedproperty 'MS_Description', 'DSeparateProperty
0. Nie dotyczy
1. Wspólnota maj¹tkowa
2. Rozdzielnoœæ maj¹tkowa
99. Nieznane', 'Schema', dbo, 'table', Individual, 'column', SeparateProperty;

EXEC sp_addextendedproperty 'MS_Description', 'Tablica zawiera dane charakteryzuj¹ce klienta instutucjonalnego (dzia³alnoœæ gospodarcza, rolnicy, spó³ki, podmioty finansowe itp.). Stanowi uzupe³nienie tablicy Customer.', 'Schema', dbo, 'table', Institutional;


EXEC sp_addextendedproperty 'MS_Description', 'Liczba poprzedzona symbolem kraju ', 'Schema', dbo, 'table', Institutional, 'column', Nip;




EXEC sp_addextendedproperty 'MS_Description', '<=0 LaunchDate <= YEAR(NOW())', 'Schema', dbo, 'table', Institutional, 'column', LaunchDate;

EXEC sp_addextendedproperty 'MS_Description', 'DAccountingForm
1. Uproszczona
2. Pe³na', 'Schema', dbo, 'table', Institutional, 'column', AccountingForm;

EXEC sp_addextendedproperty 'MS_Description', '>=0', 'Schema', dbo, 'table', Institutional, 'column', EmployessNumber;






EXEC sp_addextendedproperty 'MS_Description', 'DCurrency', 'Schema', dbo, 'table', Institutional, 'column', FinancialStatementCurrency;




EXEC sp_addextendedproperty 'MS_Description', 'DMIFID', 'Schema', dbo, 'table', Institutional, 'column', Mifid;

EXEC sp_addextendedproperty 'MS_Description', 'DRiskGroup', 'Schema', dbo, 'table', Institutional, 'column', RiskGroup;

EXEC sp_addextendedproperty 'MS_Description', 'DClaimsCategory', 'Schema', dbo, 'table', Institutional, 'column', DueCategory;

EXEC sp_addextendedproperty 'MS_Description', 'DRating', 'Schema', dbo, 'table', Institutional, 'column', CustomerRating;

EXEC sp_addextendedproperty 'MS_Description', 'DInvestmentRiskProfile', 'Schema', dbo, 'table', Institutional, 'column', InvestmentRiskProfile;

EXEC sp_addextendedproperty 'MS_Description', 'Lista klientów predefiniowanych dla danego klienta. Lista ta jest zarz¹dzana przez klienta poprzez ró¿ne kana³y dostêpu.', 'Schema', dbo, 'table', PredefCustomerList;






EXEC sp_addextendedproperty 'MS_Description', 'Lista dokumentów zwi¹zanych z klientem (a nie z rachunkami produktami). Jest to ogólna karta wzorów podpisów, KRS, CEiDG itp.', 'Schema', dbo, 'table', CustomerDoc;







EXEC sp_addextendedproperty 'MS_Description', 'DBlocadeType
0. Niezablokowany
1. PEP
2. AML
3. Zastrze¿enie dokumentów
4. Wyp³aty
5. Wp³aty
6. Wp³aty i wyp³aty', 'Schema', dbo, 'table', Blocade, 'column', BlocadeType;



EXEC sp_addextendedproperty 'MS_Description', 'Tabela relacji klienta z innymi klientami. Np. firma ma pe³nomocnika.', 'Schema', dbo, 'table', Relationship;



EXEC sp_addextendedproperty 'MS_Description', 'DRelationshipType', 'Schema', dbo, 'table', Relationship, 'column', RelationshipType;




































































































EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DEntity, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DEntity, 'column', ValidTo;



EXEC sp_addextendedproperty 'MS_Description', 'S³ownik z rolami klientów i u¿ytkowników', 'Schema', dbo, 'table', DRole;


EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko w trakcie zmiany', 'Schema', dbo, 'table', DRole, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko w trakcie zmiany', 'Schema', dbo, 'table', DRole, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DAccessType, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DAccessType, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DContributionType, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DContributionType, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DRelationshipType, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DRelationshipType, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DGroupType, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DGroupType, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DRelationshipClass, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DRelationshipClass, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DHandling0Definition, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DHandling0Definition, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DHandlingStatus, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DHandlingStatus, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DIncomeCurrency, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DIncomeCurrency, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DPost, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DPost, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DCitizenshipCountry, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DCitizenshipCountry, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DEducation, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DEducation, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DHandlingDefinition, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DHandlingDefinition, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DIncome, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DIncome, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DMaritalStatus, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DMaritalStatus, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DOccupation, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DOccupation, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DSeparateProperty, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DSeparateProperty, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DAddressType, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DAddressType, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DVoivodeship, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DVoivodeship, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DSex, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DSex, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DTitle, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DTitle, 'column', ValidTo;





EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie', 'Schema', dbo, 'table', DIdentificationType, 'column', ValidFrom;

EXEC sp_addextendedproperty 'MS_Description', 'Parametr istotny tylko przy zmianie ', 'Schema', dbo, 'table', DIdentificationType, 'column', ValidTo;
















EXEC sp_addextendedproperty 'MS_Description', 'Lista PKD z zaznaczeniem PKD g³ównego', 'Schema', dbo, 'table', Pkd;


EXEC sp_addextendedproperty 'MS_Description', 'DPKD', 'Schema', dbo, 'table', Pkd, 'column', Pkd;


EXEC sp_addextendedproperty 'MS_Description', 'DTakNie', 'Schema', dbo, 'table', Pkd, 'column', MainPkd;
